#!/bin/bash

DIR=$(dirname $0)
ARCHDEPS="vim zsh"
FEDDEPS="vim-enhanced zsh"
DEBDEPS="vim-nox zsh"
NC='\e[0m'
WHT='\e[1;37m'
GRN='\e[0;32m'

case "$1" in
	'--arch')
		ZSHRCFILE=".zshrcarch"
		OS="arch"
		;;
	'--fed')
		ZSHRCFILE=".zshrcfed"
		OS="fed"
		;;
	'--deb')
		ZSHRCFILE=".zshrcdeb"
		OS="deb"
		;;
esac

set_zshrc() {
	if [ -f $HOME/.zshrc ] ; then
		echo -e $WHT"Copy .zshrc and backup local copy?"$NC
		echo -e $GRN"\t1) Backup and copy\n\t2) Copy and replace\n\t3) Skip"$NC
		read ANS
	fi
	if [[ $ANS == '1' ]] ; then
		echo -e $WHT"Copying and backing up .zshrc to .zshrcbak"$NC
		mv $HOME/.zshrc $HOME/.zshrcbak
		cp $DIR/$ZSHRCFILE $HOME/.zshrc
	elif [[ $ANS == '2' ]] ; then
		echo -e $WHT"Copying and replacing"$NC
		cp $DIR/$ZSHRCFILE $HOME/.zshrc
	elif [[ $ANS == '3' ]] ; then
		echo -e $WHT"Skipping..."$NC
	fi
	if [ ! -f $HOME/.zshrc ] ; then
		cp $DIR/$ZSHRCFILE $HOME/.zshrc
	fi
}

inst_plugins() {
	curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh
}

inst() {
	inst_plugins
	set_zshrc
	cp $DIR/vimrc $HOME/.vimrc
	case "$OS" in
		'arch')
			TGT=`pacman -T $ARCHDEPS`
			sudo pacman -S $TGT
			;;
		'fed')
			sudo yum install $RPMDEPS -y
			;;
		'deb')
			dpkg -s $DEBDEPS >/dev/null 2>&1
			if [ "$?" -ne "0" ] ; then
				sudo apt-get install -y $DEBDEPS
			fi
			;;
	esac
	vim +NeoBundleInstall +qall
}

usage() {
	echo -e "usage: install --[distro]\n"
	echo -e "Distros:"
	echo -e "\t--arch\tInstall Arch dotfiles"
	echo -e "\t--deb\tInstall Debian dotfiles"
	echo -e "\t--fed\tInstall Fedora dotfiles"
	echo -e "\t--help\tDisplay this"
	exit
}

case "$1" in
	'--arch'|'--deb'|'--fed')
		inst
		;;
	*)
		usage
		;;
esac
